---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install curl
  - sudo apt-get install php5

install:
  - pip install ansible

  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  - >
    ansible-playbook -i tests/inventory tests/test.yml --sudo
    | grep -q 'changed=0.*unreachable=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - cd /var/www/tutu/web && php -S localhost:8000&
  - curl localhost:8000/hello/world?name=TuTu
