---
language: python
python: "2.7"

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php5
  - sudo apt-get update -qq
  - sudo apt-get install curl
  - sudo apt-get install php5
  - sudo apt-get install php5-cli
  - sudo apt-get install php5-curl

install:
  - pip install ansible==1.5.0

  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
  - cd /var/www/tutu/web
  - php -S localhost:8000 index.php &
  - curl http://localhost:8000/hello/world?name=TuTu
