---
language: python
python: "2.7"

env:
  - SITE=test.yml

before_install:
  - sudo apt-get install curl
  - sudo apt-get install php5
  e
install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"

  - php /var/www/tutu/web && php -S localhost:8000&
  - curl localhost:8000/hello/world?name=TuTu
