---
- name: Clone TuTu repository
  git:
    repo: "https://github.com/coduo/TuTu.git"
    dest: "{{ tutu_root_path }}"
    ssh_opts: "-o StrictHostKeyChecking=no"

- name: Check php version
  shell: php -v
  
- name: Download composer
  shell: curl -sS https://getcomposer.org/installer | php
  args:
    chdir: "{{ tutu_root_path }}"

- name: Intall dependencies
  shell: php composer.phar install
  args:
    chdir: "{{ tutu_root_path }}"

- name: Create TuTu configuration
  template:
    src: config.yml.js2
    dest: "{{ tutu_root_path }}/config/config.yml"

- name: Create TuTu default responses
  shell: cp {{ tutu_root_path }}/config/responses.yml.dist {{ tutu_root_path }}/config/responses.yml
